"""Add account connection state tracking for multi-account support

Revision ID: 756dae056c20
Revises: 001
Create Date: 2025-12-15 13:51:57.702421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756dae056c20'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('TRADE_OPENED', 'TRADE_CLOSED', 'DAILY_SUMMARY', 'ERROR_ALERT', 'PROFIT_THRESHOLD', 'LOSS_THRESHOLD', name='alerttype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.Column('sms_recipients', sa.Text(), nullable=True),
    sa.Column('profit_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loss_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('symbol_filter', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_configurations_alert_type'), 'alert_configurations', ['alert_type'], unique=False)
    op.create_table('currency_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=False),
    sa.Column('max_position_size', sa.Float(), nullable=False),
    sa.Column('min_position_size', sa.Float(), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('fast_period', sa.Integer(), nullable=False),
    sa.Column('slow_period', sa.Integer(), nullable=False),
    sa.Column('sl_pips', sa.Integer(), nullable=False),
    sa.Column('tp_pips', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('trade_on_signal_change', sa.Boolean(), nullable=False),
    sa.Column('allow_position_stacking', sa.Boolean(), nullable=False),
    sa.Column('max_positions_same_direction', sa.Integer(), nullable=False),
    sa.Column('max_total_positions', sa.Integer(), nullable=False),
    sa.Column('stacking_risk_multiplier', sa.Float(), nullable=False),
    sa.Column('trading_hours_start', sa.String(length=5), nullable=True),
    sa.Column('trading_hours_end', sa.String(length=5), nullable=True),
    sa.Column('additional_settings', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_loaded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_configurations_symbol'), 'currency_configurations', ['symbol'], unique=True)
    op.create_table('trading_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('login', sa.Integer(), nullable=False),
    sa.Column('password_encrypted', sa.String(length=255), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_accounts_account_number'), 'trading_accounts', ['account_number'], unique=True)
    op.create_table('account_connection_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('connection_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_connection_states_account_id'), 'account_connection_states', ['account_id'], unique=True)
    op.create_table('report_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='reportfrequency'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True, comment='For weekly reports: 0=Monday, 6=Sunday'),
    sa.Column('day_of_month', sa.Integer(), nullable=True, comment='For monthly reports: 1-31'),
    sa.Column('time_of_day', sa.String(length=5), nullable=True, comment='Time in HH:MM format (24-hour)'),
    sa.Column('report_format', sa.Enum('PDF', 'CSV', 'EXCEL', name='reportformat'), nullable=False),
    sa.Column('include_trades', sa.Boolean(), nullable=False),
    sa.Column('include_charts', sa.Boolean(), nullable=False),
    sa.Column('days_lookback', sa.Integer(), nullable=False, comment='Number of days to include in report'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='Filter by specific account, NULL for all accounts'),
    sa.Column('recipients', sa.Text(), nullable=False, comment='Comma-separated email addresses'),
    sa.Column('cc_recipients', sa.Text(), nullable=True, comment='Comma-separated CC email addresses'),
    sa.Column('email_subject', sa.String(length=200), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_configurations_account_id'), 'report_configurations', ['account_id'], unique=False)
    op.create_index(op.f('ix_report_configurations_is_active'), 'report_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_configurations_name'), 'report_configurations', ['name'], unique=False)
    op.create_index(op.f('ix_report_configurations_next_run'), 'report_configurations', ['next_run'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('TRADE_OPENED', 'TRADE_CLOSED', 'DAILY_SUMMARY', 'ERROR_ALERT', 'PROFIT_THRESHOLD', 'LOSS_THRESHOLD', name='alerttype'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEBSOCKET', name='notificationchannel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_type'), 'alert_history', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_history_sent_at'), 'alert_history', ['sent_at'], unique=False)
    op.create_index(op.f('ix_alert_history_trade_id'), 'alert_history', ['trade_id'], unique=False)
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('report_start_date', sa.DateTime(), nullable=False),
    sa.Column('report_end_date', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Execution time in milliseconds'),
    sa.ForeignKeyConstraint(['config_id'], ['report_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_config_id'), 'report_history', ['config_id'], unique=False)
    op.create_index(op.f('ix_report_history_generated_at'), 'report_history', ['generated_at'], unique=False)
    op.create_index(op.f('ix_report_history_success'), 'report_history', ['success'], unique=False)
    op.add_column('account_snapshots', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_foreign_key(None, 'account_snapshots', 'trading_accounts', ['account_id'], ['id'])
    op.add_column('daily_performance', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_daily_performance_account_id'), 'daily_performance', ['account_id'], unique=False)
    op.create_foreign_key(None, 'daily_performance', 'trading_accounts', ['account_id'], ['id'])
    op.add_column('trades', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'trading_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_column('trades', 'account_id')
    op.drop_constraint(None, 'daily_performance', type_='foreignkey')
    op.drop_index(op.f('ix_daily_performance_account_id'), table_name='daily_performance')
    op.drop_column('daily_performance', 'account_id')
    op.drop_constraint(None, 'account_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_column('account_snapshots', 'account_id')
    op.drop_index(op.f('ix_report_history_success'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_generated_at'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_config_id'), table_name='report_history')
    op.drop_table('report_history')
    op.drop_index(op.f('ix_alert_history_trade_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_sent_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_type'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_report_configurations_next_run'), table_name='report_configurations')
    op.drop_index(op.f('ix_report_configurations_name'), table_name='report_configurations')
    op.drop_index(op.f('ix_report_configurations_is_active'), table_name='report_configurations')
    op.drop_index(op.f('ix_report_configurations_account_id'), table_name='report_configurations')
    op.drop_table('report_configurations')
    op.drop_index(op.f('ix_account_connection_states_account_id'), table_name='account_connection_states')
    op.drop_table('account_connection_states')
    op.drop_index(op.f('ix_trading_accounts_account_number'), table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index(op.f('ix_currency_configurations_symbol'), table_name='currency_configurations')
    op.drop_table('currency_configurations')
    op.drop_index(op.f('ix_alert_configurations_alert_type'), table_name='alert_configurations')
    op.drop_table('alert_configurations')
    # ### end Alembic commands ###
