"""add_account_currency_configs

Revision ID: 9f0df884bcb0
Revises: a9392368ae24
Create Date: 2025-12-28 15:32:14.826498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0df884bcb0'
down_revision: Union[str, None] = 'a9392368ae24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_currency_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('min_position_size', sa.Float(), nullable=True),
    sa.Column('strategy_type', sa.String(length=20), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('fast_period', sa.Integer(), nullable=True),
    sa.Column('slow_period', sa.Integer(), nullable=True),
    sa.Column('sl_pips', sa.Integer(), nullable=True),
    sa.Column('tp_pips', sa.Integer(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('trade_on_signal_change', sa.Boolean(), nullable=True),
    sa.Column('allow_position_stacking', sa.Boolean(), nullable=True),
    sa.Column('max_positions_same_direction', sa.Integer(), nullable=True),
    sa.Column('max_total_positions', sa.Integer(), nullable=True),
    sa.Column('stacking_risk_multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_symbol'], ['currency_configurations.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'currency_symbol', name='uq_account_currency')
    )
    op.create_index(op.f('ix_account_currency_configs_account_id'), 'account_currency_configs', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_currency_configs_currency_symbol'), 'account_currency_configs', ['currency_symbol'], unique=False)
    op.add_column('account_snapshots', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_foreign_key(None, 'account_snapshots', 'trading_accounts', ['account_id'], ['id'])
    op.create_index(op.f('ix_daily_performance_account_id'), 'daily_performance', ['account_id'], unique=False)
    op.create_foreign_key(None, 'daily_performance', 'trading_accounts', ['account_id'], ['id'])
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'trading_accounts', ['account_id'], ['id'])
    op.alter_column('trading_accounts', 'platform_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('MT4', 'MT5', name='platformtype'),
               existing_nullable=False,
               existing_server_default=sa.text("'MT5'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_accounts', 'platform_type',
               existing_type=sa.Enum('MT4', 'MT5', name='platformtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'MT5'"))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_constraint(None, 'daily_performance', type_='foreignkey')
    op.drop_index(op.f('ix_daily_performance_account_id'), table_name='daily_performance')
    op.drop_constraint(None, 'account_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_column('account_snapshots', 'account_id')
    op.drop_index(op.f('ix_account_currency_configs_currency_symbol'), table_name='account_currency_configs')
    op.drop_index(op.f('ix_account_currency_configs_account_id'), table_name='account_currency_configs')
    op.drop_table('account_currency_configs')
    # ### end Alembic commands ###
